// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type EmailVerification struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type PasswordReset struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type Record struct {
	ID        int64     `json:"id"`
	Artist    string    `json:"artist"`
	Album     string    `json:"album"`
	Year      int64     `json:"year"`
	Genre     string    `json:"genre"`
	Condition string    `json:"condition"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RecordImage struct {
	ID        int64     `json:"id"`
	RecordID  int64     `json:"record_id"`
	Filename  string    `json:"filename"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
