// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Record struct {
	ID        int64     `json:"id"`
	Artist    string    `json:"artist"`
	Album     string    `json:"album"`
	Year      int64     `json:"year"`
	Genre     string    `json:"genre"`
	Condition string    `json:"condition"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
