// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error)
	// User queries
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRecord(ctx context.Context, arg DeleteRecordParams) error
	DeleteUser(ctx context.Context, id int64) error
	// Record queries
	GetRecord(ctx context.Context, arg GetRecordParams) (Record, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListRecords(ctx context.Context, userID int64) ([]Record, error)
	UpdateRecord(ctx context.Context, arg UpdateRecordParams) (Record, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
