// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error)
	DeleteRecord(ctx context.Context, id int64) error
	GetRecord(ctx context.Context, id int64) (Record, error)
	ListRecords(ctx context.Context) ([]Record, error)
	UpdateRecord(ctx context.Context, arg UpdateRecordParams) (Record, error)
}

var _ Querier = (*Queries)(nil)
