// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schema.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (
    user_id, token, expires_at
) VALUES (
    ?, ?, ?
)
RETURNING id, user_id, token, expires_at, created_at, used_at
`

type CreateEmailVerificationParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, createEmailVerification, arg.UserID, arg.Token, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (
    user_id, token, expires_at
) VALUES (
    ?, ?, ?
)
RETURNING id, user_id, token, expires_at, created_at, used_at
`

type CreatePasswordResetParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, createPasswordReset, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (
    artist, album, year, genre, condition, user_id, image_filename
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, artist, album, year, genre, condition, image_filename, user_id, created_at, updated_at
`

type CreateRecordParams struct {
	Artist        string         `json:"artist"`
	Album         string         `json:"album"`
	Year          int64          `json:"year"`
	Genre         string         `json:"genre"`
	Condition     string         `json:"condition"`
	UserID        int64          `json:"user_id"`
	ImageFilename sql.NullString `json:"image_filename"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, createRecord,
		arg.Artist,
		arg.Album,
		arg.Year,
		arg.Genre,
		arg.Condition,
		arg.UserID,
		arg.ImageFilename,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Album,
		&i.Year,
		&i.Genre,
		&i.Condition,
		&i.ImageFilename,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, first_name, last_name
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, email, password_hash, first_name, last_name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
}

// User queries
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM records 
WHERE id = ? AND user_id = ?
`

type DeleteRecordParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecord, arg.ID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users WHERE email = ?
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByEmail, email)
	return err
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT ev.id, ev.user_id, ev.token, ev.expires_at, ev.created_at, ev.used_at, u.email 
FROM email_verifications ev
JOIN users u ON ev.user_id = u.id
WHERE ev.token = ? 
  AND ev.expires_at > datetime('now')
  AND ev.used_at IS NULL
LIMIT 1
`

type GetEmailVerificationByTokenRow struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	Email     string       `json:"email"`
}

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (GetEmailVerificationByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationByToken, token)
	var i GetEmailVerificationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.Email,
	)
	return i, err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT pr.id, pr.user_id, pr.token, pr.expires_at, pr.created_at, pr.used_at, u.email 
FROM password_resets pr
JOIN users u ON pr.user_id = u.id
WHERE pr.token = ? 
  AND pr.expires_at > datetime('now')
  AND pr.used_at IS NULL
LIMIT 1
`

type GetPasswordResetByTokenRow struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	Email     string       `json:"email"`
}

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (GetPasswordResetByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByToken, token)
	var i GetPasswordResetByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.Email,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, artist, album, year, genre, condition, image_filename, user_id, created_at, updated_at FROM records 
WHERE id = ? AND user_id = ? 
LIMIT 1
`

type GetRecordParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Record queries
func (q *Queries) GetRecord(ctx context.Context, arg GetRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, arg.ID, arg.UserID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Album,
		&i.Year,
		&i.Genre,
		&i.Condition,
		&i.ImageFilename,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, created_at, updated_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRecords = `-- name: GetUserRecords :many
SELECT id, artist, album, year, genre, condition, image_filename, user_id, created_at, updated_at FROM records
WHERE user_id = ?
    AND (artist LIKE ? OR album LIKE ?) 
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetUserRecordsParams struct {
	UserID int64  `json:"user_id"`
	Artist string `json:"artist"`
	Album  string `json:"album"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) GetUserRecords(ctx context.Context, arg GetUserRecordsParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, getUserRecords,
		arg.UserID,
		arg.Artist,
		arg.Album,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Album,
			&i.Year,
			&i.Genre,
			&i.Condition,
			&i.ImageFilename,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsAsc = `-- name: GetUserRecordsAsc :many
SELECT id, artist, album, year, genre, condition, image_filename, user_id, created_at, updated_at FROM records
WHERE user_id = ?
    AND (artist LIKE ? OR album LIKE ?) 
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type GetUserRecordsAscParams struct {
	UserID int64  `json:"user_id"`
	Artist string `json:"artist"`
	Album  string `json:"album"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) GetUserRecordsAsc(ctx context.Context, arg GetUserRecordsAscParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, getUserRecordsAsc,
		arg.UserID,
		arg.Artist,
		arg.Album,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Album,
			&i.Year,
			&i.Genre,
			&i.Condition,
			&i.ImageFilename,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsCount = `-- name: GetUserRecordsCount :one
SELECT COUNT(*) 
FROM records
WHERE user_id = ?
    AND (artist LIKE ? OR album LIKE ?)
`

type GetUserRecordsCountParams struct {
	UserID int64  `json:"user_id"`
	Artist string `json:"artist"`
	Album  string `json:"album"`
}

func (q *Queries) GetUserRecordsCount(ctx context.Context, arg GetUserRecordsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserRecordsCount, arg.UserID, arg.Artist, arg.Album)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isEmailVerified = `-- name: IsEmailVerified :one
SELECT verified_at IS NOT NULL as is_verified
FROM users
WHERE id = ?
`

func (q *Queries) IsEmailVerified(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, isEmailVerified, id)
	var is_verified bool
	err := row.Scan(&is_verified)
	return is_verified, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, artist, album, year, genre, condition, image_filename, user_id, created_at, updated_at FROM records 
WHERE user_id = ? 
ORDER BY artist
`

func (q *Queries) ListRecords(ctx context.Context, userID int64) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Album,
			&i.Year,
			&i.Genre,
			&i.Condition,
			&i.ImageFilename,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications
SET used_at = CURRENT_TIMESTAMP
WHERE token = ?
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markEmailVerificationUsed, token)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET verified_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmailVerified, id)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets
SET used_at = CURRENT_TIMESTAMP
WHERE token = ?
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetUsed, token)
	return err
}

const updateRecord = `-- name: UpdateRecord :one
UPDATE records
SET artist = ?,
    album = ?,
    year = ?,
    genre = ?,
    condition = ?,
    image_filename = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, artist, album, year, genre, condition, image_filename, user_id, created_at, updated_at
`

type UpdateRecordParams struct {
	Artist        string         `json:"artist"`
	Album         string         `json:"album"`
	Year          int64          `json:"year"`
	Genre         string         `json:"genre"`
	Condition     string         `json:"condition"`
	ImageFilename sql.NullString `json:"image_filename"`
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, updateRecord,
		arg.Artist,
		arg.Album,
		arg.Year,
		arg.Genre,
		arg.Condition,
		arg.ImageFilename,
		arg.ID,
		arg.UserID,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Album,
		&i.Year,
		&i.Genre,
		&i.Condition,
		&i.ImageFilename,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecordImage = `-- name: UpdateRecordImage :one
UPDATE records
SET image_filename = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, artist, album, year, genre, condition, image_filename, user_id, created_at, updated_at
`

type UpdateRecordImageParams struct {
	ImageFilename sql.NullString `json:"image_filename"`
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
}

func (q *Queries) UpdateRecordImage(ctx context.Context, arg UpdateRecordImageParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, updateRecordImage, arg.ImageFilename, arg.ID, arg.UserID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Album,
		&i.Year,
		&i.Genre,
		&i.Condition,
		&i.ImageFilename,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = ?,
    first_name = ?,
    last_name = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, email, password_hash, first_name, last_name, created_at, updated_at
`

type UpdateUserParams struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
