// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schema.sql

package db

import (
	"context"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (
    artist, album, year, genre, condition
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, artist, album, year, genre, condition, created_at, updated_at
`

type CreateRecordParams struct {
	Artist    string `json:"artist"`
	Album     string `json:"album"`
	Year      int64  `json:"year"`
	Genre     string `json:"genre"`
	Condition string `json:"condition"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, createRecord,
		arg.Artist,
		arg.Album,
		arg.Year,
		arg.Genre,
		arg.Condition,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Album,
		&i.Year,
		&i.Genre,
		&i.Condition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM records WHERE id = ?
`

func (q *Queries) DeleteRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecord, id)
	return err
}

const getRecord = `-- name: GetRecord :one
SELECT id, artist, album, year, genre, condition, created_at, updated_at FROM records WHERE id = ? LIMIT 1
`

func (q *Queries) GetRecord(ctx context.Context, id int64) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Album,
		&i.Year,
		&i.Genre,
		&i.Condition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, artist, album, year, genre, condition, created_at, updated_at FROM records ORDER BY artist
`

func (q *Queries) ListRecords(ctx context.Context) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Album,
			&i.Year,
			&i.Genre,
			&i.Condition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecord = `-- name: UpdateRecord :one
UPDATE records
SET artist = ?,
    album = ?,
    year = ?,
    genre = ?,
    condition = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, artist, album, year, genre, condition, created_at, updated_at
`

type UpdateRecordParams struct {
	Artist    string `json:"artist"`
	Album     string `json:"album"`
	Year      int64  `json:"year"`
	Genre     string `json:"genre"`
	Condition string `json:"condition"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, updateRecord,
		arg.Artist,
		arg.Album,
		arg.Year,
		arg.Genre,
		arg.Condition,
		arg.ID,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Album,
		&i.Year,
		&i.Genre,
		&i.Condition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
