// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Artist struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Location struct {
	ID          int64
	Name        string
	Description sql.NullString
	IsDefault   sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Record struct {
	ID                int64
	Title             string
	ArtistID          sql.NullInt64
	AlbumTitle        sql.NullString
	ReleaseYear       sql.NullInt64
	CurrentLocationID sql.NullInt64
	HomeLocationID    sql.NullInt64
	CatalogNumber     sql.NullString
	Condition         sql.NullString
	Notes             sql.NullString
	LastPlayedAt      sql.NullTime
	PlayCount         sql.NullInt64
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}
