// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsDefault   pgtype.Bool        `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Record struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	ArtistID          pgtype.Int4        `json:"artist_id"`
	AlbumTitle        pgtype.Text        `json:"album_title"`
	ReleaseYear       pgtype.Int4        `json:"release_year"`
	CurrentLocationID pgtype.Int4        `json:"current_location_id"`
	HomeLocationID    pgtype.Int4        `json:"home_location_id"`
	CatalogNumber     pgtype.Text        `json:"catalog_number"`
	Condition         pgtype.Text        `json:"condition"`
	Notes             pgtype.Text        `json:"notes"`
	LastPlayedAt      pgtype.Timestamptz `json:"last_played_at"`
	PlayCount         pgtype.Int4        `json:"play_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
